import { MigrationInterface, QueryRunner } from "typeorm";

export class Init011710794345326 implements MigrationInterface {
    name = 'Init011710794345326'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accessToken" character varying NOT NULL, "refreshToken" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "ecommerce_id" uuid, CONSTRAINT "REL_25dd32088be80761d17d97867d" UNIQUE ("ecommerce_id"), CONSTRAINT "PK_1e38bc43be6697cdda548ad27a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profile_entity" ("id" SERIAL NOT NULL, "nickname" character varying NOT NULL, "registrationDate" date, "firstName" character varying, "lastName" character varying, "gender" character varying NOT NULL, "countryId" character varying NOT NULL, "email" character varying NOT NULL, "identificationNumber" character varying, "identificationType" character varying, "address" character varying, "city" character varying, "state" character varying, "zipCode" character varying, "areaCode" character varying, "extension" character varying, "phoneNumber" character varying NOT NULL, "phoneVerified" boolean NOT NULL DEFAULT false, "alternativeAreaCode" character varying, "alternativeExtension" character varying, "alternativePhoneNumber" character varying, "userType" character varying NOT NULL, "tags" text NOT NULL, "logo" character varying, "points" integer NOT NULL, "siteId" character varying NOT NULL, "permalink" character varying NOT NULL, "sellerExperience" character varying NOT NULL, "acceptCreditNote" boolean, "sellerReputationLevelId" character varying, "powerSellerStatus" character varying, "canceledTransactions" integer NOT NULL DEFAULT '0', "completedTransactions" integer NOT NULL DEFAULT '0', "totalTransactions" integer NOT NULL DEFAULT '0', "negativeRatings" integer NOT NULL DEFAULT '0', "neutralRatings" integer NOT NULL DEFAULT '0', "positiveRatings" integer NOT NULL DEFAULT '0', "salesCompleted" integer, "claimsRate" integer, "claimsValue" integer, "delayedHandlingTimeRate" integer, "delayedHandlingTimeValue" integer, "canceledBuyerTransactions" integer NOT NULL DEFAULT '0', "buyerTags" text NOT NULL, "notRatedTransactions" integer NOT NULL DEFAULT '0', "unratedTransactions" integer NOT NULL DEFAULT '0', "confirmedEmail" boolean NOT NULL DEFAULT true, "mercadoenviosStatus" character varying NOT NULL, "mercadopagoAccountType" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ecommerce_id" uuid, CONSTRAINT "UQ_91e458b17f494faaf95d534ac94" UNIQUE ("nickname"), CONSTRAINT "REL_cd033a66c148a8536f3b0a17c9" UNIQUE ("ecommerce_id"), CONSTRAINT "PK_330d3560db0dac16f06a04609bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ecommerce" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50), "code" character varying(50), "app_id" character varying(50), "client_secret" character varying(50), "redirect_uri" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid, "ecommerce_id" integer, CONSTRAINT "REL_9197dccc4e5ced38c6fb94b806" UNIQUE ("ecommerce_id"), CONSTRAINT "PK_e67660bf2a224d8ce3d2b1b57ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_roles_enum" AS ENUM('admin', 'professional', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50), "lastname" character varying(50), "email" character varying(100) NOT NULL, "number" character varying(20), "roles" "public"."users_roles_enum" NOT NULL DEFAULT 'user', "password" character varying(100), "deleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipping_entity" ("id" SERIAL NOT NULL, "status" character varying NOT NULL, "shipping_status" character varying NOT NULL, "tracking_number" character varying NOT NULL, "shipping_method" character varying NOT NULL, "order_id" integer NOT NULL, "order_cost" integer NOT NULL, "base_cost" integer NOT NULL, "site_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_23ec35ef7f3e6c1878c1a20e32d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."admins_roles_enum" AS ENUM('admin', 'professional', 'user')`);
        await queryRunner.query(`CREATE TABLE "admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50), "lastname" character varying(50), "email" character varying(100) NOT NULL, "roles" "public"."admins_roles_enum" NOT NULL DEFAULT 'admin', "password" character varying(100), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_051db7d37d478a69a7432df1479" UNIQUE ("email"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD CONSTRAINT "FK_25dd32088be80761d17d97867da" FOREIGN KEY ("ecommerce_id") REFERENCES "ecommerce"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile_entity" ADD CONSTRAINT "FK_cd033a66c148a8536f3b0a17c90" FOREIGN KEY ("ecommerce_id") REFERENCES "ecommerce"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecommerce" ADD CONSTRAINT "FK_0a9478a6bcfa0be3b3fde372604" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecommerce" ADD CONSTRAINT "FK_9197dccc4e5ced38c6fb94b8061" FOREIGN KEY ("ecommerce_id") REFERENCES "profile_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ecommerce" DROP CONSTRAINT "FK_9197dccc4e5ced38c6fb94b8061"`);
        await queryRunner.query(`ALTER TABLE "ecommerce" DROP CONSTRAINT "FK_0a9478a6bcfa0be3b3fde372604"`);
        await queryRunner.query(`ALTER TABLE "profile_entity" DROP CONSTRAINT "FK_cd033a66c148a8536f3b0a17c90"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP CONSTRAINT "FK_25dd32088be80761d17d97867da"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP TYPE "public"."admins_roles_enum"`);
        await queryRunner.query(`DROP TABLE "shipping_entity"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_roles_enum"`);
        await queryRunner.query(`DROP TABLE "ecommerce"`);
        await queryRunner.query(`DROP TABLE "profile_entity"`);
        await queryRunner.query(`DROP TABLE "credentials"`);
    }

}
